### ISSUE TITLE
Cannot build with arm-linux-androideabi

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang/time#60]
Cannot build when using the cross compiler for arm-linux-androideabi

`rustc 1.0.0-dev (89c4e3792 2015-01-17 10:58:43 +0000)`

~~~
   Compiling time v0.1.12
     Running `/home/nathan/Development/projects/face-blaster/target/build/time-7c7fc3eb0c12ad75/build-script-build`
Build failed, waiting for other jobs to finish...
failed to run custom build command for `time v0.1.12`
Process didn't exit successfully: `/home/nathan/Development/projects/face-blaster/target/build/time-7c7fc3eb0c12ad75/build-script-build` (status=101)
--- stdout
TARGET = Some("arm-linux-androideabi")
OPT_LEVEL = Some("0")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
CARGO_MANIFEST_DIR = Some("/home/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.12")
OUT_DIR = Some("/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out")
running: arm-linux-androideabi-gcc '-O0' '-c' '-ffunction-sections' '-fdata-sections' '-fPIC' '/home/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.12/src/time_helpers.c' '-o' '/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out/src/time_helpers.o'

--- stderr
thread '<main>' panicked at 'failed to spawn process: no such file or directory', ../../../.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.4/src/lib.rs:122
~~~

**Comment by alexcrichton** [comment]
On android gcc-rs [by default](https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L151-L161) uses `arm-linux-androideabi-gcc`, is that executable in your PATH?

**Comment by nathansizemore** [comment]
It was not.  I added it, and this is the output...


~~~
nathan@jarvis ~/Development/projects/face-blaster $ which arm-linux-androideabi
/usr/bin/arm-linux-androideabi
nathan@jarvis ~/Development/projects/face-blaster $ which arm-linux-androideabi-gcc
/usr/bin/arm-linux-androideabi-gcc
nathan@jarvis ~/Development/projects/face-blaster $ cargo build --target=arm-linux-androideabi --verbose

failed to run custom build command for `time v0.1.12`
Process didn't exit successfully: `/home/nathan/Development/projects/face-blaster/target/build/time-7c7fc3eb0c12ad75/build-script-build` (status=101)
--- stdout
TARGET = Some("arm-linux-androideabi")
OPT_LEVEL = Some("0")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
CARGO_MANIFEST_DIR = Some("/home/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.12")
OUT_DIR = Some("/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out")
running: arm-linux-androideabi-gcc '-O0' '-c' '-ffunction-sections' '-fdata-sections' '-fPIC' '/home/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.12/src/time_helpers.c' '-o' '/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out/src/time_helpers.o'
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
AR_arm-linux-androideabi = None
AR_arm_linux_androideabi = None
TARGET_AR = None
AR = None
running: arm-linux-androideabi-ar 'crus' '/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out/libtime_helpers.a' '/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out/src/time_helpers.o'

--- stderr
thread '<main>' panicked at 'failed to spawn process: no such file or directory', ../../../.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.5/src/lib.rs:122
~~~

**Comment by alexcrichton** [comment]
The last few lines may be of interest:

```
running: arm-linux-androideabi-ar 'crus' '/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out/libtime_helpers.a' '/home/nathan/Development/projects/face-blaster/target/arm-linux-androideabi/build/time-7c7fc3eb0c12ad75/out/src/time_helpers.o'

--- stderr
thread '<main>' panicked at 'failed to spawn process: no such file or directory', ../../../.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.1.5/src/lib.rs:122
```

Is `arm-linux-androideabi-ar` installed?

**Comment by nathansizemore** [comment]
It was, but didn't have it in path either.  Thanks for the help.
